name: Build and Test

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      # TODO: Remove these 2 steps after May 13, 2024.
      # See https://github.com/actions/runner-images/issues/9701 for details.
      - name: Delete components
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToRemove= @(
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM64.Spectre"
          )
          [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          # should be run twice
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

      - name: Install components
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToAdd= @(
            "Microsoft.VisualStudio.Component.VC.14.39.17.9.ARM64"
            "Microsoft.VisualStudio.Component.VC.14.39.17.9.ARM64.Spectre"
            "Microsoft.VisualStudio.Component.VC.14.39.17.9.x86.x64"
            "Microsoft.VisualStudio.Component.VC.14.39.17.9.x86.x64.Spectre"
          )
          [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          # should be run twice
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        id: cache
        with:
          path: ./build/release/third_party/install
          key: ${{ github.job }}-${{ hashFiles('./third_party/**') }}-4
      - name: disable superbuild on cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
            echo "superbuild=-DSUPERBUILD=OFF" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "cmake_prefix_path=-DCMAKE_PREFIX_PATH=$(pwd)/build/release/third_party/install" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: install packages
        run: |
            choco install nasm
            echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: configure
        run: cmake -G "Visual Studio 17 2022" $env:superbuild $env:cmake_prefix_path -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/release/install -DBUILD_MAVSDK_SERVER=ON -DBUILD_SHARED_LIBS=OFF -DWERROR=ON -Bbuild/release -S.
      - name: build
        run: cmake --build build/release -j2 --config Release --target install
      - name: Create zip file mavsdk libraries
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd build/release/install && 7z.exe a -tzip ../../../mavsdk-windows-x64-release.zip . && cd ../../..
      - name: Publish mavsdk libraries
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'mavsdk-windows-x64-release.zip'
          asset_name: 'mavsdk-windows-x64-release.zip'
          tag: ${{ github.ref }}
          overwrite: true
      - name: Publish mavsdk_server binary
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/release/install/bin/mavsdk_server_bin.exe'
          asset_name: 'mavsdk_server_win32.exe'
          tag: ${{ github.ref }}
          overwrite: true
