name: Build and Test

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:

  ubuntu-superbuild:
    name: ${{ matrix.ubuntu_image }} (mavsdk_server, superbuild)
    runs-on: ${{ matrix.ubuntu_image }}
    strategy:
      matrix:
        ubuntu_image: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install pymavlink dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-future
      - name: install stuff to debug
        run: sudo apt-get install -y autoconf automake autotools-dev build-essential ca-certificates ccache cmake colordiff git libcurl4-openssl-dev libltdl-dev libtinyxml2-dev libtool libz-dev ninja-build python3 python3-pip python3-future ruby-dev software-properties-common sudo wget
      - name: configure
        run: cmake $superbuild $cmake_prefix_path -DCMAKE_BUILD_TYPE=Release -DBUILD_MAVSDK_SERVER=ON -DWERROR=OFF -Bbuild/release -H.
      - name: build
        run: cmake --build build/release -j2
      - name: install
        run: sudo cmake --build build/release --target install
      - name: install examples dependencies
        run: sudo apt-get install -y libsdl2-dev
      - name: configure examples
        run: (cd examples && cmake -DCMAKE_BUILD_TYPE=Release -DWERROR=OFF -Bbuild -H.)
      - name: build examples
        run: (cd examples && cmake --build build -j2)
      - name: unit tests
        run: ./build/release/src/unit_tests_runner
      - name: system tests
        run: ./build/release/src/system_tests/system_tests_runner
      - name: test (mavsdk_server)
        run: ./build/release/src/mavsdk_server/test/unit_tests_mavsdk_server
      - name: test FTP server
        run: ./build/release/src/integration_tests/integration_tests_runner --gtest_filter="FtpTest.TestServer"

